### ISSUE TITLE
Recordings - change display and behaviour of search results

### ISSUE THREAD

**Issue by saracoutinho** [TheCacophonyProject/cacophony-browse#149]
See https://xbn8fg.axshare.com/#id=hpb2y9&p=recordings_list&view=default&g=1
(a [few tips](https://docs.google.com/document/d/1VEM0A3UmL0p4MctywCkBLk4lyh4IqejfK5JSIJlrW7E/edit) on how to use the prototype)

Change search results to "cards" instead of displaying them in a table format.

This should make the search results more usable on mobile. It’s still debatable if having them in a card format is better on desktop. If we find out a table is better, there are a couple of options:
- Change search results to a table/table look-a-like on desktop
- Allow toggling between displays (by clicking on a table view/card view button) on desktop and remember this choice

Most of the card should be clickable to navigate to the single recording page. **Don't** open the recording page in a new tab.

**Tags**
Display more information about who tagged that item. If it was the AI, show a cog. If it was a person, show the user icon. Hovering the tag displays the name of the entity/person(s) that added the tag.

**Map**
Show if available. Might need to toggle between road/topographical maps depending on the device location.

**Comment by hardiesoft** [comment]
I've been doing some work towards this, and I have a question about the map thumbnail functionality.  How is this imagined to work?  Can it be assumed that it is a service that would be provided by the cacophony API, where it would create or fetch map thumbnails from some third-party mapping service?

**Comment by arthurmcgregor** [comment]
I've had some experience with client-side webmaps if we decide to go that route rather than server-side. [mapbox-gl-vue](https://www.npmjs.com/package/mapbox-gl-vue) with [Mapbox](https://www.mapbox.com/) api or [vue2-leaflet](https://www.npmjs.com/package/vue2-leaflet) with free [leaflet providers](https://leaflet-extras.github.io/leaflet-providers/preview/)

**Comment by mjs** [comment]
TBH, I haven't thought too hard about where the maps would come from but a third party mapping provider seem preferable to me. As for whether maps are fetched client-side or server-side, I don't have a strong preference. I guess this depends somewhat on the way the mapping service works. From a quick look, it seems that MapBox leans strongly toward client-side access.

Pricing is also a factor. We are not adverse to paying but are cost sensitive. Free is obviously good as long as it gives us what we need. 

Mapbox and the free Leaftlet providers both seem workable. I know a GIS expert that I can ask for advice on this too. Perhaps start with the other changes for this screen and I'll get back to you.

**Comment by hardiesoft** [comment]
@mjs Cool, I'll just make it a placeholder for now.  @arthurmcgregor I think whatever we do it really wants to just be a thumbnail image, rather than a full-blown mapping service embedded widget, since that could mean we'd need to instantiate ~300 map component instances per page, which would not be great.  A mapping component could make sense for the recording detail page though.

**Comment by hardiesoft** [comment]
Found this website that has a good overview of various static map apis: https://staticmapmaker.com - perhaps using mapbox from here?

**Comment by mjs** [comment]
Agreed that we don't want interactive maps for each search result - a static image would be fine. An interactive map when viewing an individual recording would be good to have though.

Let's aim to use the same service for both the static and interactive maps though. It would be nice if the maps had the same style and look in both places.

**Comment by hardiesoft** [comment]
When a user specifies a relative date range, such as "Last 24 hours", or "Last three days" should this be handled at an API level, so the API would have a concept of CURRENT_DATE - duration as a span, rather than, or in addition to the current recordingDateTime["$lt"], recordingDateTime["$gt"] query?  It would be easy enough to translate the relative ranges into absolute date ranges on the front-end, and supply only absolute ranges to the API query, but then you'd lose the ability to meaningfully bookmark/share those search settings.

Another option that would keep the benefit of sharing/saving relative date queries would be to just have that information on the client-side query param that gets stuffed into the browser history, and then always decode that to the current absolute range when sending the query off to the api, but this starts to involve more book-keeping since now the api query has diverged from the one we store in the url.  Maybe this isn't a big deal, since it's sort of an incidental implementation detail that they *are* currently the same query string.  Thoughts?

**Comment by mjs** [comment]
I'm open to the API server understanding the relative date ranges but this would swap one form of sharability for another. For example, what if you want to share a specific range of recordings with someone? If the URL included "last 24 hours" then when the other person looked at the URL they could end up seeing a different set of recordings than the sender intended. This behaviour might be hard to for a user to grok.

Given that users will often have access to different sets of devices and recordings, sharing of search result URLs probably won't be that common/useful so perhaps we shouldn't be optimising for that  case. A user bookmarking a often used search for themselves will probably be more likely, in which case teaching the API server about relative date ranges would be helpful.

On a related note, I *really* don't like our APIs where we take a general `where` field which is passed straight to the API server's ORM. They're hard to use, introduce unnecessary security surface and tie us to the ORM. Hence this issue: https://github.com/TheCacophonyProject/cacophony-api/issues/180

**Comment by mjs** [comment]
Getting back to maps... I've heard back from our GIS advisor who said that both Leaflet and Mapbox are great.

What they both actually are is a little confusing. I found this explanation quite helpful: https://stackoverflow.com/questions/12262163/what-are-leaflet-and-mapbox-and-what-are-their-differences/23663848#23663848

How about we try using:
- static Mapbox tiles as per https://staticmapmaker.com for the search results screen
- Leaflet with Mapbox tiles or Mapbox.js (with Vue helpers as appropriate) when viewing a specific recording

@arthurmcgregor mentioned he had used the WebGL Mapbox maps but I wonder how well WebGL works on a wide variety of browsers (especially on mobile). I'm fairly ignorant regarding WebGL so perhaps it's fine but I'd like to see how well it works on mid range phones.

**Comment by hardiesoft** [comment]
Close, and maybe open a new issue for the map thumb?
