### ISSUE TITLE
Add indication on device list to show type

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/cacophony-browse#25]
Indicate audio device (:speaker: ) or thermal device (:film_strip:)

**Comment by arthurmcgregor** [comment]
I think this requires an API change and presumably some change in the device registration process because from what I can see the 'get list of devices' endpoint does not return any information about the type of recordings produced by that device. Although you could run a recordings query to see what sort of recordings are returned by each device, that seems like a rather overblown approach!

@mjs I suggest this issue is closed as not worth the time or effort...
